baseURL = "https://yanlipnican.github.io"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hyde"
publishDir = ""
disqusShortname = "blog-lipnican"
pygmentsCodeFences = true
pygmentsUseClasses = true